### ISSUE TITLE
How to try this out?

### ISSUE THREAD

**Issue by parkerlreed** [Medformatik/CrossDrop#1]
Wanting to give this a shot, but have no clue where to start building it.

**Comment by parkerlreed** [comment]
After a bit of trial and error, figured out flutter!

```
(1)(deck@steamdeck CrossDrop)$ sudo chown -R deck:deck /usr/local
(deck@steamdeck CrossDrop)$ flutter build linux

💪 Building with sound null safety 💪
Building Linux application... 
```

Having trouble getting the device to show up when searching for a target from the phone.

**Comment by parkerlreed** [comment]
Is the UI not hooked up to backend currently? Not seeing any open ports for the CrossDrop PID on my system.

**Comment by Medformatik** [comment]
Hello, great that you found CrossDrop. You have seen correctly that CrossDrop doesn't work yet. As stated in the README.md, this is still a work in progress and the only thing I have implemented until now is a basic UI. The functionality itself is what comes next. Therefore, there is no compiled software for the installation.

**Comment by blurskye** [comment]
why no aur/flatpak/deb version?

**Comment by Loup-Garou911XD** [comment]
> why no aur/flatpak/deb version?

It's not even in alpha stages yet

**Comment by Medformatik** [comment]
Unfortunately I didn't have time to work on this for a long time. However, a few days ago I started with a new UI and now finally with the implementation of Nearby/Quick Share. I think I'm making good progress to "translate" the Swift code to Dart, but I don't have a working version yet. I hope that I can publish a first version soon.

**Comment by danielesca** [comment]
Hi, so glad someone is working on it. I have been looking onto this for a long time, but being a junior developer (just graduating this year) I can't get to work on this all by myself. I found [this repo](https://github.com/vicr123/QNearbyShare) but can't build it (library errors and more) but it seems to have all functionality so it may be useful for this project. As I said, I'm very inexperienced but if I could be of any help I would be willing to help you on anything if I'm capable of in case you need it :)
