### ISSUE TITLE
Device not showing up to other devices

### ISSUE THREAD

**Issue by sidevesh** [Medformatik/CrossDrop#5]
I noticed that the app does not get detected by Nearby Share on Android,
I tested on Linux, is this known ?
I saw that you mentioned that the sharing functionality is WIP in the README.

**Comment by Medformatik** [comment]
Yes, that's right. So far this repository contains only the UI preparations, the functionality itself is not yet fully implemented. I still have local changes that I haven't committed yet, in which I have already implemented some parts of Nearby Share. As soon as I get that done, I'll commit the code as soon as possible, of course. However, it should be obvious that implementing Nearby Share is not that trivial, so I'll have to see how soon I can get it working.

**Comment by Medformatik** [comment]
Duplicate #1
