### ISSUE TITLE
Need help with building

### ISSUE THREAD

**Issue by Loup-Garou911XD** [Medformatik/CrossDrop#8]
after running `flutter build linux`
`./build/linux/x64/release/bundle/CrossDrop`

i get this error
```
(CrossDrop:7604): Gdk-CRITICAL **: 19:37:29.670: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel macos_window_utils/window_manipulator)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320)
<asynchronous suspension>
#1      WindowManipulator.initialize (package:macos_window_utils/window_manipulator.dart:42)
<asynchronous suspension>
#2      MacosWindowUtilsConfig.apply (package:macos_ui/src/macos_window_utils_config.dart:71)
<asynchronous suspension>
#3      main (package:crossdrop/main.dart:39)
<asynchronous suspension>


```

**Comment by Medformatik** [comment]
Duplicate #2.

This is a work in progress. It is not yet feature-complete, and it is not yet stable. I have started building this for macOS first (as you can see in the error), so this does not work on other platforms.
At the moment I don't have the time to work on implementing Nearby Share here, even though that's what it's all about. I've started working on it, but I don't have the time to finish it at the moment (check [README](https://github.com/PlutoHDDev/CrossDrop/blob/main/README.md)).
